---
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install stacker==1.7.0
  build:
    commands:
      - stacker build offsite/stacks/offsite-full-env.yaml